[package]
name = "wasm-pack-example"
version = "0.1.0"
authors = ["Florent Bécart <florentb@wix.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = "0.2"

[dev-dependencies]
wasm-bindgen-test = "0.2"
